name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-release:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
      
    - name: ArchiveProcess run
      run: swift run ArchiveProcess
      
    - name: ArchiveProcess release
      run: ArchiveProcess release
      
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: |
          .build/release/ArchiveProcess-Intel.zip
